### ISSUE TITLE
udocker error

### ISSUE THREAD

**Issue by bitcometz** [biowdl/QC#33]
Hello,

I want to run the QC pipeline in my cluster with udocker since I do not have root authority.

So I first udocker pull all the images:
$udocker ps
CONTAINER ID                         P M NAMES              IMAGE
e27faa98-0311-3951-ae53-32236a4f46ad . W ['biopet-extractadaptersfastqc'] quay.io/biocontainers/biopet-extractadaptersfastqc:0.2--1
9d204993-11e4-3531-b9d4-32490d116f40 . W ['fastqc']         quay.io/biocontainers/fastqc:0.11.7--4
3b1f6f10-9ae0-3c1f-a15c-5efa32843652 . W ['cutadapt']       quay.io/biocontainers/cutadapt:2.3--py36h14c3975_0

and arrange three containers named '**biopet-extractadaptersfastqc**', '**fastqc**', and '**cutadapt**'.
Then I edit the file **tasks/fastqc.wdl**
to
    runtime {
        cpu: threads
        **docker: "fastqc"**
    }
and the file **tasks/cutadapt.wdl** to
    runtime {
        cpu: cores
        memory: memory
        docker: "cutadapt"
    }

and then edit the backend file for udocker:
include required(classpath("application"))

docker.hash-lookup.enabled = false

backend {
  default = udocker

  providers {
    udocker {
        # The backend custom configuration.
        actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"

        config {
            run-in-background = true
            runtime-attributes = """
              String? docker
             """
             submit-docker = """
             source /HWNAS12/RAD/zhangjinbo/02.testP/03.tests/05.WDL/QC/env.sh
             udocker run \
              --user $(id -u $USER) \
              -v ${cwd}:${docker_cwd} \
              -v /HWNAS12/RAD/zhangjinbo/02.testP/03.tests/05.WDL/QC:/HWNAS12/RAD/zhangjinbo/02.testP/03.tests/05.WDL/QC \
              -v /tmp:/tmp \
              ${docker} /bin/bash ${script}
             exit 1
	     """
             filesystems {
               local {
                  localization: ["hard-link", "soft-link"]
               }
             }
        }
    }
}
}

and I run:
**java -Dconfig.file=udocker2.conf -jar cromwell-41.jar run -i inputs.json QC.wdl**

Actually I think I have finished the fastqc(I set Boolean runAdapterClipping = false) jobs because I got results in the output dir: *.html and *.zip

However, I got error information :

 [2019-06-27 17:54:48,41] [error] WorkflowManagerActor Workflow 316f1deb-50be-44a7-8c68-470be3cca9da failed (during ExecutingWorkflowState): Job QC.FastqcRead2:NA:1 exited with return code -1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /HWNAS12/RAD/zhangjinbo/02.testP/03.tests/05.WDL/QC/cromwell-executions/QC/316f1deb-50be-44a7-8c68-470be3cca9da/call-FastqcRead2/execution/stderr.
 [First 300 bytes]:Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell-executions/QC/316f1deb-50be-44a7-8c68-470be3cca9da/call-FastqcRead2/tmp.64783ef0

Could you help me with this problem? Something wrong with my backend file ?

Best,

**Comment by DavyCats** [comment]
It looks like your submit-docker contains the line `exit 1`, this may cause cromwell to believe that the submission of the job failed. `exit 1` will cause the script to be exited with a return code of `1`, which means failed. Changing this to `exit 0` or removing this line altogether might fix this issue.

On a side note, since you mentioned you are running this on a cluster, are you sure your submission command is approriate? I don't know what kind of cluster you are using, but generally you will want to submit the jobs to execution nodes (eg. with `qsub` for SGE or `sbatch` for SLURM). The submission command here will run udocker on whatever node you are running cromwell from.
You might want to have a look here: https://cromwell.readthedocs.io/en/stable/backends/HPC/ to see how to configure your backend for a cluster. Just so you are aware.

**Comment by bitcometz** [comment]
Thanks for your help !!! Problem solved ！！！
I'm a little out of my mind ^-^

**Comment by bitcometz** [comment]
hello, 
today, I used cromwell server successfully qsub my jobs with udocker and my backend file is:

include required(classpath("application"))

webservice {
    port = 8001
    interface = 0.0.0.0
}

docker.hash-lookup.enabled = false

backend {
  default = udocker

  providers {
    udocker {
        # The backend custom configuration.
        actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"

        config {
            run-in-background = true
            runtime-attributes = """
              String? docker
             """
             submit-docker = """
             echo 'source /HWNAS12/RAD/zhangjinbo/02.testP/03.tests/05.WDL/QC/env.sh
             udocker run \
              --user $(id -u $USER) \
              -v ${cwd}:${docker_cwd} \
              -v /HWNAS12/RAD/zhangjinbo/02.testP/03.tests/05.WDL/QC:/HWNAS12/RAD/zhangjinbo/02.testP/03.tests/05.WDL/QC \
              -v /tmp:/tmp \
              ${docker} /bin/bash ${script}' > ${script}.docker.sh
             qsub \
              -V \
              -N udocker \
              -wd ${cwd} \
              -o tmp.out \
              -e tmp.err \
              -l vf=1g,p=1 \
	      ${script}.docker.sh
	     """
             filesystems {
               local {
                  localization: ["hard-link", "soft-link"]
               }
             }
        }
    }
  }
}

Is there a better way to write it ?

Thanks!!!

**Comment by DavyCats** [comment]
This looks okay to me.
You could probably pipe the udocker command into qsub though, instead of writing it to a file first. And you could probably use `${out}` and `${err}` instead of `tmp.out` and `tmp.err`, that way the stdout and stderr get saved alongside the scripts in the cromwell-execution folders.
eg.:
```bash
echo 'source /path/udocker_env.sh
      udocker run \
        --user $(id -u $USER) \
        -v ${cwd}:${docker_cwd} \
        -v /path/05.WDL/QC:/path/05.WDL/QC \
        -v /tmp:/tmp \
        ${docker} /bin/bash ${script}' | \
qsub \
  -V \
  -N ${job_name}_udocker \
  -wd ${cwd} \
  -o ${out] \
  -e ${err} \
  -l vf=1g,p=1
```

If you have any further questions on how to configure cromwell, broad's wdl/cromwell forums might be a more suitable place. The people there probably know more about how to do this properly. https://gatkforums.broadinstitute.org/wdl
